### ISSUE TITLE
PHP 7.4 support (upgrade monolog, dependencies)

### ISSUE THREAD

**Issue by d8vjork** [optimizely/php-sdk#191]
Hi there 🙋‍♂

Tests seems to fail on PHP 7.4, 7.3 still fine though.

Another problem that I don't know is that if this package will upgrade its dependencies like Monolog, because I'm writing a wrapper/integration with Laravel for one of my projects so it requires monolog 2.x from Laravel and so it has dependencies conflicts (specially with monolog)

**Comment by Afrowson** [comment]
I am a Software developer at www.aboalarm.de This is also a major issue for us. 
We want to use optimizely, but our internal logging and Laravel use monolog/monolog 2.0.

Please fix this asap :)

**Comment by d8vjork** [comment]
@Afrowson I was also looking into the same thing creating a package to bring this to Laravel

**Comment by jeffochoa** [comment]
✋ facing the same issue here. Laravel user as well.

**Comment by fbnfgc** [comment]
Any update about PHP 7.4 support? [As mentionned](https://github.com/optimizely/php-sdk/pull/192#issuecomment-595708578) by @d8vjork, this package supports 5.5, 5.6, 7.0 and 7.1 which are [out of support](https://www.php.net/supported-versions.php).

PHP 7.4 has been released at the end of 2019. Four months ago [PHP 7.4 represented 20% of the projects](https://blog.packagist.com/php-versions-stats-2020-1-edition/). 

Have you considered bumping a major version to drop old PHP versions? 

Thanks!

**Comment by jjmu15** [comment]
I desperately want to use this in my Laravel application also but have the same problem. Any chance of this getting actioned soon as it seems to have been stagnant for a long time? :(

**Comment by zashraf1985** [comment]
We just removed the restriction of `monolog` version from the sdk. We have tested it with php `8.1.2` along with `monolog` version `2.3` and it appears to be working. Please update PHP SDK version to `3.9.0` and it should work.
