### ISSUE TITLE
Wrong phpdocs for method `lookup` in  interface UserProfileServiceInterface

### ISSUE THREAD

**Issue by rolandsusans** [optimizely/php-sdk#258]
## The bug reported 🐛 

There is a typo in `phpdocs` here: 

https://github.com/optimizely/php-sdk/blame/master/src/Optimizely/UserProfile/UserProfileServiceInterface.php#L26

Because there is no class with name `userProfile`. 
Seems like intention was to specify `UserProfile` or `array` instead.

## Background
In some case insensitive file systems, like MacOS APFS (default). It's impossible to have `userProfile.php` and `UserProfile.php` in same directory. Meanwhile in case sensitive file systems it's possible.

In my use case specifying return type hint as `userProfile` (by sdk) is causing issues when trying to add ignore configuration to `ignoreErrors` in `phpstan-baseline.neon`. During the execution of phpstan on each filesystem, the error list is different - because of case insensitivity and type specified in phpdocs.

**Comment by rolandsusans** [comment]
After thinking a while on this it's not actually clear what was the original intention of the phpdoc. 
https://github.com/optimizely/php-sdk/blame/master/src/Optimizely/UserProfile/UserProfileServiceInterface.php#L26

was it `UserProfile` or `UserProfile[]` or `array<string,UserProfile>` 🤔

**Comment by rolandsusans** [comment]
Looking at https://github.com/optimizely/php-sdk/blame/master/src/Optimizely/UserProfile/UserProfileServiceInterface.php#L33 seems that it should be an `array`. Right @fullstack-devs?

**Comment by mikechu-optimizely** [comment]
Hi @rolandsusans, I just closed your PR since we published a patch version to Packagist.  

Is this Issue resolved?
