### ISSUE TITLE
Deprecated: Creation of dynamic property Optimizely\ProjectConfigManager\HTTPProjectConfigManager::$isDatafileAccessTokenValid is deprecated

### ISSUE THREAD

**Issue by wadekarrahul** [optimizely/php-sdk#277]
Getting a Deprecated warning on php 8.2.

Deprecated: Creation of dynamic property Optimizely\ProjectConfigManager\HTTPProjectConfigManager::$isDatafileAccessTokenValid is deprecated in /vendor/optimizely/optimizely-sdk/src/Optimizely/ProjectConfigManager/HTTPProjectConfigManager.php on line 97

**Comment by mikechu-optimizely** [comment]
Thanks for reporting @wadekarrahul.  We are looking for how to best provide guidance and steering in a "go forward" for this SDK. 

For now, have you considered adjusting your `error_reporting(E_ALL & ~E_DEPRECATED);`?

Also, feel free to submit a Pull Request with a modification to the codebase.

**Comment by mikechu-optimizely** [comment]
Merged to main branch.
