### ISSUE TITLE
monolog version

### ISSUE THREAD

**Issue by dfreudenberger** [optimizely/php-sdk#31]
Hey there,

do we really need to fix monolog/monolog to a specific version? As of right now the sdk requires version ```1.21.0``` and I would be surprised if something like ```^1.21.0``` doesn't work as well. 

Best,
Daniel

**Comment by aliabbasrizvi** [comment]
@dfreudenberger @Spea this fix should be available in release 1.1.0

**Comment by aliabbasrizvi** [comment]
Marking this issue as resolved
