### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by resourcemode** [optimizely/php-sdk#87]
composer unable to pickup and install php-sdk due to the error below.

**First Attempt:**

➜  registration git:(develop) ✗ composer require optimizely/optimizely-sdk:1.5.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package optimizely/optimizely-sdk could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Second Attempt:**
➜  registration git:(develop) ✗ composer require optimizely/optimizely-sdk      

                                                                                                                                                             
  [InvalidArgumentException]                                                                                                                                 
  Could not find package optimizely/optimizely-sdk at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
                                                                                                                                                             

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by aliabbasrizvi** [comment]
@resourcemode thank you for reaching out regarding the issue. We will take a look and get back to you.

**Comment by aliabbasrizvi** [comment]
Hi @resourcemode 

I tried installing and the install was successful on my end. Can you share the exact command you are running to do the installation? Are you specifying the package in `composer.json`? 

Here is how I mentioned it in `composer.json` to install:

```
  "require": {
    "optimizely/optimizely-sdk": "^1.5"
  }
```

I also tried installing directly by running the command: `php composer.phar require optimizely/optimizely-sdk` and noticed no issues.

Let me know more details on how you are attempting the installation.

Thanks

**Comment by resourcemode** [comment]
Thanks for the reply, we decided to use google optimize instead. 

You can see the command and output I executed in first attempt and second attempt above.
